### ISSUE TITLE
No way to access GUI features in newer gnome release (3.26+)

### ISSUE THREAD

**Issue by dogtopus** [codestation/qcma#101]
Newer version of gnome blocks systray applet, which causes the GUI features of QCMA become inaccessable.

**Comment by codestation** [comment]
On what distro? Newer Qt versions shouldn't have problems with this. Newer Ubuntu versions shows the icon and they moved from old style icons too.

**Comment by dogtopus** [comment]
Not sure what you mean by "newer Qt". If Qt changes its behavior (e.g. use gnome notification system to trigger the systray menu or whatever) after the systray icon deprecation/block was done on the gnome side, I can certainly try again and report back since last time I tried this was 3 months ago.

By the way I am using ArchLinux and installed qcma-git from AUR. The Qt I am using comes from the official distro repository.

**Comment by dogtopus** [comment]
Just tried it, still not working. QCMA starts but there is no way to recall the GUI nor exit it normally (except via `killall -SIGINT qcma` or similar).

I guess Ubuntu made it work by either added patches to gnome or qt, or shipped gnome with some extensions that re-enables systray icon (I knew an extension that got abandoned by its maintainer that did exactly this. Not sure if someone else forked it and made it work again), or used outdated gnome that didn't block systray applets.

**Comment by codestation** [comment]
After reading https://wiki.gnome.org/Initiatives/StatusIconMigration/Guidelines it seems that Gnome doesn't support traditional tray icons nor status icons or appindicators. While i don't expect legacy tray icons to be supported, i find idiotic the decision of Gnome to hide status icons and don't even support appindicators.

As a workaround use https://extensions.gnome.org/extension/615/appindicator-support/, use qcma-cli or drop Gnome. Qcma doesn't have or need a main window so it doesn't fit Gnome guidelines.

I'll close this as WONTFIX.
