### ISSUE TITLE
qcma hangs after restoring a backup

### ISSUE THREAD

**Issue by Lykie** [codestation/qcma#102]
Every time I restore a system backup, qcma hangs and I have to kill process then start it up again.

Tested with Ubuntu 16.04 and a PS TV.

**Comment by codestation** [comment]
Sorry, don't have a PSTV for testing. WiFi seems unstable, it happens on USB too?

**Comment by IgorAkimov1995** [comment]
yes, it hangs even via USB, what command is to kill the process?
