### ISSUE TITLE
CLI interaction/flags

### ISSUE THREAD

**Issue by fyr77** [codestation/qcma#108]
Hi!
Can QCMA be controlled using CLI? So far I wasn't able to do so.
Thanks in advance!

**Comment by codestation** [comment]
In what way? CMA itself doesn't have much room for configuration. All the settings are on the config file and the location cannot be changed.

For now the only flags/signals available for qcma_cli are defined [here](https://github.com/codestation/qcma/blob/master/cli/qcma_cli.1).

**Comment by fyr77** [comment]
Apparently I can't read, I'm sorry. I somehow overlooked that.
