### ISSUE TITLE
QCMA Sometimes Requires a Restart

### ISSUE THREAD

**Issue by ccfman2004** [codestation/qcma#112]
I am using Mac OS X 10.13.5 and quite frequently (especially on the PSTV) I have to restart QCMA before my PSTV will connect properly.

Also I have to select quit twice for the app to fully quit and then sometimes crashes.

Both PS Vita-1000 and PSTV on Enso 3.65 spoofed to 3.68.

**Comment by codestation** [comment]
Recompiled Qcma for High Sierra using newer libraries, dunno if it helps. Also are you using USB or WiFi? the later is somewhat unstable anyway.
