### ISSUE TITLE
The PC has been disconnected

### ISSUE THREAD

**Issue by sigve10** [codestation/qcma#113]
Every time I try to connect my PS Vita to QCMA, it connects for about 20 seconds, flashes a message for about a fifth of a second (too short for me to read what it says) followed by my computer giving me the "device connected" and "device disconnected" noises in succession, then my PS Vita gives me the message "The PC has been disconnected". My PS Vita is on FW 3.65, and QCMA 0.4.1. I'm running Windows 10.

I have tried about everything that I could find through google searches (reinstalling/replacing drivers, reinstalling QCMA) and none of them fix the problem. I checked through the issues posted here and none of them seemed to have the same problem as I did.

I tried to retrieve a log, but whenever I opened it in either console or the log mode I found in [here](https://github.com/codestation/qcma/issues/80), it would refuse to connect (it still connects in the regular mode).

Please... send help.

**Comment by codestation** [comment]
Use a different cable or USB port. Some usb drivers (3.0) have been known to interfere with libusb drivers. Also make sure that the official CMA isn't running.

**Comment by sigve10** [comment]
I've attempted using 3 different USBs on two different USB ports. None of them have yielded any results. I also do not have the official sony CMA installed.
