### ISSUE TITLE
QCMA 0.4.1 doesn't add 3.65 PUP to database

### ISSUE THREAD

**Issue by ivdok** [codestation/qcma#114]
I need to revert to stock 3.65 without updating further, but following the guides for manual update doesn't work. Summary:

1. Downloaded PSP2UPDAT.PUP, size 133 754 368 bytes, MD5 0a0f2a9ae58968ac5d1d2127049c3cba, SHA-1 a957f3cce99abf2081212b34582633a662874621.
2. Created psp2-updatelist.xml with following contents: [https://pastebin.com/F4S9xeLP](https://pastebin.com/F4S9xeLP)
3. Put it all under /mnt/hdd/QCMA/Updates
4. "Updates / Web content" set to /mnt/hdd/QCMA/Updates
5. Following settings inside QCMA: [https://i.imgur.com/sVqUb4C.png](https://i.imgur.com/sVqUb4C.png)
6. Refreshing Database returns "Added 0 items"
7. I think I must also mention that this mobo is not activated, which caused issues in the past, but shouldn't QCMA at least acknowledge there's something in Updates folder?

Question is, what did I miss, and how to fix this? Any help is appreciated.
I tried steps above both on Windows and Linux, only difference is updates path.

**Comment by codestation** [comment]
2) You need to use the correct region id (isn't always "us"). Is better to delete the xml and let Qcma generate one on the fly with the correct values (check the corresponding box in settings).
6) The database is only for PSVita content, the update is read directly
7) Qcma (same with Official CMA) is useless if the Vita isn't activated. You could try to boot in safe mode and try to update from there. I never tried but it shouldn't check the activation status from there.
