### ISSUE TITLE
Add a catagory for rePatch?

### ISSUE THREAD

**Issue by ness151** [codestation/qcma#116]
with the recent updates to game patching (translations, etc), would it be possible to add a category for rePatch? So on backup it can scan for the rePatch dir on ux0 for matching titleID folders and back those up, and on restore it can restore a matching rePatch titleID dir or ask to restore said folder along with the game/save data?

**Comment by TheRadziu** [comment]
tbh we could add such feature to repatch itself, then make some condition in qcma so repatch dir is skipped for people without the plugin
