### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [codestation/qcma#118]
i've downloaded Version '0.4.1' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFShortVersionString** entries in your Info.plist file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by codestation** [comment]
I generate the application using macdeployqt, i guess that it doesn't add the version info. This will have to wait until i streamline the build process on macOS so i can add the missing fields.

**Comment by core-code** [comment]
ok thanks. i'll look into macdeployqt, if it doesn't add the version numbers then thats a bug i'll report to them.
