### ISSUE TITLE
Error installing Qcma on Ubuntu 18.10

### ISSUE THREAD

**Issue by wrdavid** [codestation/qcma#123]
This is the output i get every time:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'qcma' instead of './qcma_0.4.2_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qcma : Depends: libavcodec57 (>= 7:3.4.2) but it is not installable or
                 libavcodec-extra57 (>= 7:3.4.2) but it is not installable
        Depends: libavformat57 (>= 7:3.4.2) but it is not installable
        Depends: libavutil55 (>= 7:3.4.2) but it is not installable
        Depends: libswscale4 (>= 7:3.4.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by daviel** [comment]
Same for me
