### ISSUE TITLE
QCMA doesnt backup license.psvimg for Piyotama (PSP) 

### ISSUE THREAD

**Issue by KuromeSan** [codestation/qcma#132]
It seems it just *doesnt* create a license.psvimg for it,
it does in offical CMA though ...

**Comment by codestation** [comment]
Sorry, don't have a Vita not the game to debug this. Weird bug since CMA is a dummy client and the Vita is the one that sends the files to the PC, CMA doesn't even know what files is receiving.

**Comment by KuromeSan** [comment]
seems to happen with quite a few psp games..

also LocoRoco: Midnight Carnival - NPUG80318?
