### ISSUE TITLE
USB Not Workinkg

### ISSUE THREAD

**Issue by dnarock666** [codestation/qcma#135]
My specifications are:

-Windws 10 Home Edition x64 bit
-QCMA
-Not CMA installed
-Usb cable working only in charging battery
-PS Vita 1000 with 3.65 Enso installed
-Working recharging port
-USB Win Driver installed by QCMA

When I try to plug my vita in every single port with QCMA running, nothing's happening.

Why my PC doesn't make even a plug device sound?

**Comment by codestation** [comment]
Does it work with the official CMA? Most of the time is because a faulty cable or some outdated USB 3.0 controller.

**Comment by dnarock666** [comment]
I tried with:
-Original CMA (uninstalling QCMA first)
-Reinstalling Windows
-Buying another PS Vita datasync cable

Still like Windows never knows there's a PS Vita plugged..

P.S.: VitaShell says USB is connected, but nothing happens

**Comment by codestation** [comment]
If CMA doesn't work either then there isn't much that i can do. Since you have Vitashell you could use the usb option instead as that doesn't require an additional driver.
