### ISSUE TITLE
Psvita soft blocked error C0-10139-4

### ISSUE THREAD

**Issue by Yolomation** [codestation/qcma#137]
My PS vita keeps having this error. I've tried everything and watched every tutorial but i cant seem to find a solution. It would be much appreciated if you were to respond.

**Comment by fennectech** [comment]
What’s going on with the vita. Are you able/willing to do a factory reset via safe mode?

**Comment by Yolomation** [comment]
Damn! turned out it was just a plate of ravioli the whole time!
