### ISSUE TITLE
Provide Debian 10 repositories

### ISSUE THREAD

**Issue by jstolarek** [codestation/qcma#138]
Official QCMA page provides links to Debian 9.0 repositories. However, version 10 of Debian is available since July 2019, and the version 9 repository does not work with version 10 of Debian. It would be nice to have a repository for the current stable version of Debian.

**Comment by codestation** [comment]
Done, i found out what was the problem with OBS and it let me build the Debian 10 packages.

https://software.opensuse.org//download.html?project=home%3Acodestation&package=qcma

**Comment by jstolarek** [comment]
That was quick. Thanks! I can confirm that it works.
