### ISSUE TITLE
Failed to Build 

### ISSUE THREAD

**Issue by Samurai-of-death** [codestation/qcma#22]
I can't get qcma to build using the AUR package https://aur.archlinux.org/packages/qcma-git/

Here is a paste bin of what outputs when I try to compile this 

http://pastebin.com/YZUJ1Zvu

**Comment by Samurai-of-death** [comment]
seems the current AUR show the package as needing vitamtpmod and not vitamtpmod-git so I compiled with vitamtpmod-git and it works and runs fine :)

**Comment by jcgargma** [comment]
qcma-git is not the official aur for qcma, as it is maintained by someone else.
Use https://aur.archlinux.org/packages/qcma instead, as it is the one maintained by codestation.

**Comment by codestation** [comment]
Do you have qtchooser installed? I modified the PKGBUILD to use the correct version of qdbuscpp2xml.

If installing qtchooser fix your problem then i either add it as a build time dependency or switch to build with Qt5.

**Comment by Samurai-of-death** [comment]
I do have qtchooser installed but I did notice your new PKGBUILD command workaround notice the command is wrong for qt4. Should look something like this http://pastebin.com/3CqfCdvf

That might be the reason for the build failing

**Comment by Shemagh** [comment]
Trying to install from AUR. Do have qtchooser and all dependencies but still unable to build the package.

Sorry to say but I'm a noob, and I can't code or modify PKGBUILD so I'm kind of at a loss as to what to do. 

Here's a paste of the output: http://pastebin.com/tamSbfr4

**Comment by codestation** [comment]
Can you execute this command? `ls --color=auto -l /usr/bin/qdbusxml2cpp*`

Broken symlinks will show on red. This is mine btw, and the PKGBUILD works fine:

    lrwxrwxrwx 1 root root  9 dic 13 13:20 /usr/bin/qdbusxml2cpp -> qtchooser
    lrwxrwxrwx 1 root root 29 dic 14 13:14 /usr/bin/qdbusxml2cpp-qt4 -> /usr/lib/qt4/bin/qdbusxml2cpp
    lrwxrwxrwx 1 root root 28 ene 20 09:57 /usr/bin/qdbusxml2cpp-qt5 -> /usr/lib/qt/bin/qdbusxml2cpp

**Comment by Shemagh** [comment]
The output of that command was this:

lrwxrwxrwx 1 root root  9 Dec 13 17:50 /usr/bin/qdbusxml2cpp -> qtchooser
lrwxrwxrwx 1 root root 29 Dec 14 17:44 /usr/bin/qdbusxml2cpp-qt4 -> /usr/lib/qt4/bin/qdbusxml2cpp

I'm glad you posted yours too, because I noticed qt5 also being required. Installed qt5 and the pkgbuild worked perfectly.

**Comment by Samurai-of-death** [comment]
I just check and current PKGBUILD does work and build just fine for me.

**Comment by codestation** [comment]
Closing this since qcma now uses Qt5 by default.
