### ISSUE TITLE
adding to Debian archive

### ISSUE THREAD

**Issue by a-detiste** [codestation/qcma#23]
Hi,

You have taken so many efforts to build a nice .deb ; why not ask to add your package to the Debian archive ?

You may think of the ITP (Intent To Package) process as a bit circimonvoluted; I can do most steps for you if you like, and upload to mentors.debian.org where a Debian Developper will review it once again and push it in the archive.

**Comment by codestation** [comment]
I haven't tried to submit into any official channels because i still lack some understanding about packaging. For example the mentors FAQ says that i shouldn't put the debian directory in the repository (or the orig package) but i am not sure where it belongs then.

Also i am writting the changelogs by hand where the file looks like that it should be generated automatically by some tool. (Or if i shouldn't be patching the changelog at all, since i make debs for other ubuntu distros).

If you can help me with that then i agree to add qcma to the debian archive.

**Comment by a-detiste** [comment]
In Debian there is never one true way to do something, and even the FAQ are disputed.

This advice is there because the `debian/` folder shipped by upstreams is regularly of poor quality and it's easier to start over. As you are already using debuild & lintian; this can as well be made a `native` package. Going the other way would mean to manage a duplicate Git three only for packaging & with little gain.

I see that QCAM is using CDBS and vitamtp use debhelper; any objection to use debhelper for both ? 
CDBS is mostly end-of-live now.

If your package get in Debian, it will trickle automatically in Ubuntu distros too, of course.

I'm not yet a proper "Debian Developper", but I'm member of the Game Team and can help your two packages go through the process.

I'll have a look later at the changelog problem.

**Comment by codestation** [comment]
All the debian/rules examples that i found using Qt/qmake make use of cdbs, any idea on how to remove the dependency on it?

**Comment by a-detiste** [comment]
> Also i am writting the changelogs by hand where the file looks like that it should be generated automatically by some tool.

This tool is called `dch` in the `devscript` package

**Comment by a-detiste** [comment]
> If you can help me with that then i agree to add qcma to the debian archive.

Please define "help": I can fill the two ITP bugs (Intent To Package) & advertise on debian-devel mailing list + push the packages to mentors.debian.org ; or is reviewing here enough and you will handle the paperwork by yourself ?

* qcma is done

* for libmtp4, I guess some would say the udev rule with `0666` is not secure enough in a shared environment; where a theorical other local user could try to trash your PS Vita... that would justify a postinst script that create a dedicated user group for use with a `0660` mode + users having to add themselve to that group + logoff/logon at first install; that is much pain for a theorical threat.

**Comment by codestation** [comment]
> Please define "help"

Just to clarify some stuff as i don't want to screw it up on the next version:

For example the source format (quilt vs native). If i use native i cannot apply patches to the sources. In vitamtp 2.5.7 ppa package i had to switch back to quilt to apply a patch and solve a bug that i found after i tagged the release.

I am not sure if using native over quilt has some significance or what method is more accepted to fix bug in a source tarball: provide a patch vs make a new tag/tarball just for a quick bugfix (as i cannot move the original tag or the hashes will not match anymore).

About the ITP+push: i already created an account on mentors.debian.net and i am familiar with the dput command (i use it to upload to launchpad.net ppa build system). Also i was gonna use [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=770915) as a template for the ITP bug report. I am missing anything?

For libvitamtp4, i agree that having o+w permission is not secure and other packages already creates their own group to provide some security when accesing devices (like wireshark and virtualbox).  I will include a message in bold text to remind the users to add themselves to the vitamtp group and aso the application will inform the user if they aren't included in that group.

**Comment by a-detiste** [comment]
> quilt vs native

Well, your package have been native one since "forever" .. ChangeLog is even a symlink to debian/changelog, and I don't know how apt-get / aptitude will behave if the same package exists as a native and non-native with same version in main repos + leftover ppa.

>  a bug that i found after i tagged the release 2.5.7

Native packages would solve this by tagging 2.5.7.1 with a one-line erratum changelog that says this is a Debian/Ubuntu-only release; you may well not rebuild it for all old Ubuntu versions/other distros if not needed.

>  template for the ITP bug report

this is it.  
you can either carefully craft the mail pseudo-headers Package / Severity / Owner, or let `reportbug` do some of the work; then the `bts` command line let you manage/triage existing bugs.
(you can install `nullmailer` if you don't want to mess with a real MTA just for `bts`)

> vitamtp

Nice !  
In most cases, main real user has id 1000, so most users would find this nice:
`adduser $(getent passwd 1000 | cut -f1 -d\:) vitamtp`
but some not, so that would need a debconf prompt or some discussion on debian-devel mailing list.
http://www.fifi.org/doc/debconf-doc/tutorial.html

If you find this `0660` access too restrictive for your Ubuntu PPA, you can well use `dpkg-vendor --query Vendor` to dynamicaly change how your package is built.

Example:
https://github.com/mvo5/unattended-upgrades/blob/debian/sid/debian/rules
https://github.com/mvo5/unattended-upgrades/tree/debian/sid/data

**Comment by a-detiste** [comment]
> a bug that i found after i tagged the release 2.5.7

you can well put  2.5.7.1 in a throw-away branch you'd only use for patches to that release,
systemd is packaged that way in Debian/Ubuntu http://anonscm.debian.org/cgit/pkg-systemd/systemd.git/

**Comment by codestation** [comment]
The best is that i switch to use only two version digits for releases (e.g: 0.4.0) and use revisions (e.g.: 0.4.1) if some problem arises.

For the group stuff, IMHO the best is that the users add themselves to the vitamtp group, as using an static id won't work for systems with multiple normal users.

They can run the following command then re-log on their session:

    sudo gpasswd -a $(id -urn) ftp

I will roll 660 permissions to all Linux packages. The users won't miss this change as both GUI and cli will inform the user if they aren't in the vitamtp group when they enable the USB connection.

Thanks for the dpkg-vendor tip, this can be useful later on.

**Comment by a-detiste** [comment]
> if systemd files are supported

well, systemd is soon the new default in Ubuntu

**Comment by codestation** [comment]
Systemd isn't gonna be a problem since i intend to drop support for oldstable now that jessie is the new stable. Sorry for the lack of responses as IRL issues keep me away from the project. I intend to finish this issue after #34 is resolved.

**Comment by a-detiste** [comment]
> IRL issues

Don't worry good to hear from you again
