### ISSUE TITLE
Skip Photo, Video, Music Scanning?

### ISSUE THREAD

**Issue by wilflare** [codestation/qcma#29]
thanks for this app! I really like the GUI!
I can't figure what Skip Photo, Video, Music Scanning does in the whole scheme of things.
hope you can shed some light

**Comment by codestation** [comment]
If these are enabled then qcma won't scan these directories and the vita will not see your multimedia files. For example I have like +200 GiB of music and the initial scan of qcma for that directory will take too long so I can skip the music folder scan and qcma will only index my photos/videos.

**Comment by wilflare** [comment]
I see thanks for the prompt reply!
so does it skip the scanning on the PC side or the Vita side?

**Comment by codestation** [comment]
PC side. and yes, is better to don't send audio, video or files from the Vita to the PC if you disabled the corresponding option because it could overwrite files with the same name.
