### ISSUE TITLE
[Issue] Vita cannot reconnect after recovering from Standby

### ISSUE THREAD

**Issue by wilflare** [codestation/qcma#31]
My Vita is connected to my PC (Win8.1 Pro) via WiFi
Everything works - Until my Vita enters Standby...
- After recovering from Standby, the Vita cannot connect to QCMA
- The error on the Vita says "Could not connect to network"

In order to fix this, I need to completely shutdown QCMA and restart it before my Vita can connect
- is this how it is supposed to work?

**Comment by codestation** [comment]
Are you using the latest qcma? There are some bugs on the latest firmwares that only happens on wifi but probably cannot solve then until i fix #30

**Comment by wilflare** [comment]
hello! yea I think so.. 0.3.9 is the latest right? :X
