### ISSUE TITLE
QMCA cannot detect PS TV on same network

### ISSUE THREAD

**Issue by korgano** [codestation/qcma#32]
Been running a PS TV on Firmware 3.50 and trying to get QCMA to detect it. The PC (Windows 8.1 64 bit) and the PS TV are on the same network and I've tried adding a proxy to the PS TV's connection, which didn't do anything.

**Comment by codestation** [comment]
Make sure that qcma isn't blocked on the windows firewall. If you cancelled the firewall popup that comes when you first run qcma then you will have to enter the firewall application rules and allow qcma to receive new connections.

**Comment by codestation** [comment]
Continued on #42
