### ISSUE TITLE
qcma refuses to run at all.

### ISSUE THREAD

**Issue by 133794m3r** [codestation/qcma#33]
It keeps saying "cannot open USB connection". I've tried uninstalling and reinstalling and noting. Where is the config files for this thign stored at? I am on 3.51 and used the latest version for wheezy as I don't yet want to upgrade/was feeling lazy.

Starting QCMA 0.3.9
Current locale: "en_US"
Cannot load translation for locale: "en_US"
Starting main thread: 0x00007fa943f3d800
Current desktop:  ""
Cannot load libqcma_appindicator plugin
Starting cma threads
Starting usb_thread: 0x00007fa92a91a700
Using protocol mode:  "automatic"
Starting wireless_thread: 0x00007fa92a119700
Waiting for wireless connection
VitaMTP: waiting for connection
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
Killed

**Comment by 133794m3r** [comment]
I cannot edit the above post, but my vita was workign fine and didn't want to have to go back into windows to ust make a quick backup.

**Comment by a-detiste** [comment]
> Where is the config files for this thign stored at?

.config/codestation/qcma.conf

Was upgraded to 3.52 today, still working fine. Using Debian testing with an old build of QCMA.
Can you provide the lasts USB-related lines of `dmesg` ?

**Comment by codestation** [comment]
Are you using the latest stable vitamtp library? Check if you have the file at `/lib/udev/rules.d/80-psvita.rules` and force a rule reload with `udevadm control --reload`.

Note: if you compiled and installed vitamtp from the testing branch then you have to add yourself to the vitamtp group so qcma can connect to the vita via the usb port.

**Comment by 133794m3r** [comment]
I'll try it again in debian and as I said I just got the debs asI was feeling lazy. Also the windows one does the same thing. "No vita is registered" error even though it shows up _fine_ in cma.

**Comment by 133794m3r** [comment]
sager-laptop kernel: [ 1688.497218] usb 4-1.1: new high-speed USB device number 4 using ehci-pci
Jun 28 13:17:02 sager-laptop kernel: [ 1688.590815] usb 4-1.1: New USB device found, idVendor=054c, idProduct=04e4
Jun 28 13:17:02 sager-laptop kernel: [ 1688.590825] usb 4-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 28 13:17:02 sager-laptop kernel: [ 1688.590830] usb 4-1.1: Product: "PS Vita" Type B
Jun 28 13:17:02 sager-laptop kernel: [ 1688.590835] usb 4-1.1: Manufacturer: SONY
Jun 28 13:17:02 sager-laptop kernel: [ 1688.590839] usb 4-1.1: SerialNumber: xxxx
Jun 28 13:17:27 sager-laptop kernel: [ 1713.797142] usb 4-1.1: USB disconnect, device number 4
Jun 28 13:17:27 sager-laptop kernel: [ 1713.994208] usb 4-1.1: new high-speed USB device number 5 using ehci-pci
Jun 28 13:17:27 sager-laptop kernel: [ 1714.087710] usb 4-1.1: New USB device found, idVendor=054c, idProduct=04e4
Jun 28 13:17:27 sager-laptop kernel: [ 1714.087719] usb 4-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 28 13:17:27 sager-laptop kernel: [ 1714.087724] usb 4-1.1: Product: "PS Vita" Type B
Jun 28 13:17:27 sager-laptop kernel: [ 1714.087727] usb 4-1.1: Manufacturer: SONY
Jun 28 13:17:27 sager-laptop kernel: [ 1714.087731] usb 4-1.1: SerialNumber: xxxx
Jun 28 13:17:39 sager-laptop kernel: [ 1726.351695] usb 4-1.1: USB disconnect, device number 5
Jun 28 13:17:41 sager-laptop kernel: [ 1727.561176] usb 4-1.1: new high-speed USB device number 6 using ehci-pci
Jun 28 13:17:41 sager-laptop kernel: [ 1727.654032] usb 4-1.1: New USB device found, idVendor=054c, idProduct=04e4
Jun 28 13:17:41 sager-laptop kernel: [ 1727.654036] usb 4-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 28 13:17:41 sager-laptop kernel: [ 1727.654045] usb 4-1.1: Product: "PS Vita" Type B
Jun 28 13:17:41 sager-laptop kernel: [ 1727.654047] usb 4-1.1: Manufacturer: SONY
Jun 28 13:17:41 sager-laptop kernel: [ 1727.654048] usb 4-1.1: SerialNumber: xxxx
Jun 28 13:17:51 sager-laptop kernel: [ 1737.702010] usb 4-1.1: USB disconnect, device number 6
Jun 28 13:17:51 sager-laptop kernel: [ 1737.901796] usb 4-1.1: new high-speed USB device number 7 using ehci-pci
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995147] usb 4-1.1: New USB device found, idVendor=054c, idProduct=04e4
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995153] usb 4-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995156] usb 4-1.1: Product: "PS Vita" Type B
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995158] usb 4-1.1: Manufacturer: SONY
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995160] usb 4-1.1: SerialNumber: xxxx
Jun 28 13:17:51 sager-laptop kernel: [ 1737.901796] usb 4-1.1: new high-speed USB device number 7 using ehci-pci
Jun 28 13:17:51 sager-laptop mtp-probe: checking bus 4, device 7: "/sys/devices/pci0000:00/0000:00:1d.0/usb4/4-1/4-1.1"
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995147] usb 4-1.1: New USB device found, idVendor=054c, idProduct=04e4
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995153] usb 4-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995156] usb 4-1.1: Product: "PS Vita" Type B
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995158] usb 4-1.1: Manufacturer: SONY
Jun 28 13:17:51 sager-laptop kernel: [ 1737.995160] usb 4-1.1: SerialNumber: xxxx
Jun 28 13:17:51 sager-laptop mtp-probe: bus: 4, device: 7 was not an MTP device

**Comment by codestation** [comment]
Can you run this command with the vita connected with the usb cable?

```
ls -l $(lsusb | grep "04e4:054c" | sed 's|Bus \([0-9]\+\) Device \([0-9]\+\).*|/dev/bus/usb/\1/\2|')
```

**Comment by 133794m3r** [comment]
crw-rw-r-T 1 root root 189, 4 Jun 28 16:10 /dev/bus/usb/001/005

**Comment by 133794m3r** [comment]
I have used mtpfs before on debian and was able to mount/use my phone(s) by updating the udev rules so I don't know why this one's not connecting. I also realizd that it's 664 for some reason.

**Comment by codestation** [comment]
As a workaround you could create a file named /etc/udev/rules.d/99-psvita.rules
```
SUBSYSTEM=="usb", ATTR{product}=="*PS Vita* Type B", GROUP="vitamtp", MODE="0660"
```
Then create a system group with

```
groupadd --system vitamtp
```

And lastly add yourself to the vitamtp group (gpasswd -a myuser vitamtp), then log out & log in.

This group based permission is more secure than putting the usb device at 666 and will be the default on the next version (vitamtp 2.5.7).

The 99 in the udev rules filename will make sure that is one of the last rules to be applied so less things will interfere with it.

**Comment by 133794m3r** [comment]
Well on my laptop the windows drivers only work for one of the ports. Maybe 2 if you can fiddle with it. It's the standard usb2.0 port, and the ESATA/USB2 port on the back. the left side's usb3 ports do nothing without the mb drivers/intel's drivers.

OK it was working then gave me a seg fault here's the log just above that fault.

Event received in void CmaEvent::vitaEventSendStorageSize(vita_event_t*, int), code: 0xc119, id: 32
Storage stats for drive containing OHFI 10, free: 338183172096, total: 580298735616
Ended event, code: 0xc119, id: 32
Sending new event
Event received in void CmaEvent::vitaEventSendStorageSize(vita_event_t*, int), code: 0xc119, id: 33
Storage stats for drive containing OHFI 14, free: 338183172096, total: 580298735616
Ended event, code: 0xc119, id: 33
Sending new event
Event received in void CmaEvent::vitaEventGetTreatObject(vita_event_t*, int), code: 0xc122, id: 34
Called quint16 CmaEvent::processAllObjects(metadata_t&, quint32), handle: 67108869, parent name: 
Segmentation fault


I was trying to find a way to get thepkg to install as psm for unity is freaking 27MiB and the eml is ~30MiB nd I know of _no_ email provider that supports that size of emails including attchments.

**Comment by codestation** [comment]
Reopen if the same problem persist with 0.4.1
