### ISSUE TITLE
avcodec -> ffmpeg

### ISSUE THREAD

**Issue by a-detiste** [codestation/qcma#35]
Debian is now transitioning to ffmpeg (and avcodec fork will likely be left to die)

https://lwn.net/Articles/607591/

Needs changes in `debian/control`

**Comment by codestation** [comment]
Seems like the deps are gonna change to

```
libavformat-ffmpeg-dev
libswscale-ffmpeg-dev
```

But i only see the packages in sid so it seems too early to make the change. Reopening when debian stretch enter freeze phrase.
