### ISSUE TITLE
Sending files to psv without touching psv

### ISSUE THREAD

**Issue by nenadalm** [codestation/qcma#39]
Hi. Is it possible to send files into psv via some command?

My use case would be to setup cronjob to download my subscriptions from youtube using https://rg3.github.io/youtube-dl/, then convert the videos using https://www.ffmpeg.org/ and then automatically copy all videos when I connect psv to the pc https://unix.stackexchange.com/questions/28548/how-to-run-custom-scripts-upon-usb-device-plug-in

**Comment by codestation** [comment]
Sadly no. The PSV is the one that starts the commands so CMA is like a dumb endpoint that only answers whatever the PSV asks it to do.
