### ISSUE TITLE
Build failed: Cannot open translations/*.ts

### ISSUE THREAD

**Issue by 5685C4A059D5** [codestation/qcma#40]
Though renaming the files in translations works, installation from AUR will fail.

```
==> Starting build()...
lrelease error: Cannot open ../qcma/resources/translations/*.ts: No such file or directory
==> ERROR: A failure occurred in build().
```

**Comment by codestation** [comment]
Bumped qcma PKGBUILD to 0.3.10. If you are talking about `qcma-git` then contact sl1pkn07 since i am not maintaining the -git packages.

**Comment by sl1pkn07** [comment]
done
