### ISSUE TITLE
Cannot connect to PSTV

### ISSUE THREAD

**Issue by trumpet205** [codestation/qcma#42]
As titled. Rather than necro bumping another thread I choose to open this new one. I'm running Windows 10 x64 and PSTV (FW 3.57) just can't find qcma. I checked Windows firewall and qcma is not blocked by it.

PSTV is connected to LAN by Ethernet, and PSTV can go online like PSN or web browser.

**Comment by trumpet205** [comment]
Here is a follow up. Tried using Wi-Fi instead of Ethernet on PSTV and it works. Is there any reason why Qcma only works on specifically Wi-Fi connection for PSTV? My PC is still using Ethernet connection. 

Before switching to Wi-Fi on PSTV I tried turning off Windows Firewall as well as adding TCP/UDP port 9309 to router port forwarding settings and Qcma still can't pick up my PSTV.

In short:
Works: PSTV -- (Wi-Fi) --> Router -- (Ethernet) --> PC
Doesn't work: PSTV -- (Ethernet) --> Router -- (Ethernet) --> PC

**Comment by codestation** [comment]
Dunno, i don't own a PSTV to make tests with it.

Can you upload a [Wireshark](https://www.wireshark.org/download.html) capture file? Monitor your ethernet interface, start Qcma, connect your PSTV to the cable and try to connect from the PSTV (30 seconds is enough).

Try to don't use any other app who uses the network while doing this so the capture file is small (and eliminates the chance that personal information ends in the capture file).

**Comment by ChihiroFujimi** [comment]
Just to comment on the problem :
I got it working on Vita TV with LAN (with latest version : 3.61) building the latest GIT on Slackware 14.2 32bits. (PC and VTV are on static IP on my LAN, with 2 switches in between)
The connection itself worked ok (even if it took several minutes for the VitaTV to detect the PC)
There was a latency before being able to transfer the first file (worked only on my third try).
