### ISSUE TITLE
Backup Manager "Online ID/Username" doens't show multiple accounts

### ISSUE THREAD

**Issue by johnsonlin** [codestation/qcma#45]
Backup Manager "Online ID/Username" only shows the last connected PS vita account.
I have 2 vitas with 2 different accounts (different regions too). I can only see the account of the last vita I transfered data from/to.

**Comment by johnsonlin** [comment]
I'm on Windows 10 64bit if that helps.

**Comment by codestation** [comment]
It is a known issue. The feature isn't implemented and i was about to remove the selector in the next release since nobody ever asked for the feature.

I will fix the selector issue for 0.3.13.

**Comment by johnsonlin** [comment]
Oh, lucky me!
Thanks so much!
I look forward to your next release : )
