### ISSUE TITLE
Qcma does not run 

### ISSUE THREAD

**Issue by jbaig77** [codestation/qcma#49]
I have all packages/dependencies installed to run qmca. I run qmca in the terminal, and i get this output:
"qcma: error while loading shared libraries: libavformat.so.56: cannot open shared object file: No such file or directory"
I found out that liabavformat is provided by ffmpeg, but i have double checked that that is installed.
I am running fedora 24.
Thanks.

**Comment by codestation** [comment]
The current package is for Fedora 23, i need to recompile it for Fedora 24...... or maybe try with one of these flatpak stuff,

**Comment by codestation** [comment]
You can find current builds for Fedora 24 on the link below.

[Fedora 24](http://codestation.nekmo.com/qcma/0.3.12/fedora_24/)
