### ISSUE TITLE
Fedora 24

### ISSUE THREAD

**Issue by Xodiced** [codestation/qcma#51]
I was wondering if you plan on making packages for F24, as packages were updated for the latest Ubuntu.

Is this in the works?  Or are you waiting for the next version?  If that is the case is there an ETA for the 0.3.13(?)?

**Comment by codestation** [comment]
Sorry about that, i have zero free time these months. You can find current builds for Fedora 24 on the link below.

[Fedora 24](http://codestation.nekmo.com/qcma/0.3.12/fedora_24/)
