### ISSUE TITLE
Error C0-10139-4

### ISSUE THREAD

**Issue by Jamakusi** [codestation/qcma#53]
Having an issue when i try to update.
C0-10139-4
Only thing i could found on the internet was that it has something to do with the region (not confirmed) but i tried every region now and it failed every time

**Comment by codestation** [comment]
Are you trying to install a manual update by the "Update by Connecting to a PC]"? Instead of running qcma.exe do the following:

Open cmd and run the following commands:

```
cd %PROGRAMFILES%\Qcma
qcma_console.exe --verbose
```

Try to update until you get the error, close qcma and paste the log here.

**Comment by Jamakusi** [comment]
Thanks for trying to help me :)
I want to uptade my PS Vita to version 3.60 manual by updating it via pc

Here the logs:

C:\Program Files\Qcma>qcma_console.exe --verbose
Starting Qcma 0.3.12
Current locale: "de_DE"
Cannot load translation for locale: "de_DE"
Starting main thread: 0x00000000000011f4
Starting cma threads
Starting usb_thread: 0x0000000000001490
Using protocol mode:  "automatic"
Starting Starting database_thread: 0x0000000000001b38
wireless_thread: 0x0000000000002fd0
Waiting for wireless connection
Added VitaMTP: waiting for connection
objects for OHFI 0x01: 0
Added objects for OHFI 0x02: 2583
Added objects for OHFI 0x03: 1
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 0
Added objects for OHFI 0x0A: 0
Added objects for OHFI 0x0D: 6
Added objects for OHFI 0x0E: 0
Added objects for OHFI 0x10: 0
Added objects for OHFI 0x12: 0
Total entries added to the database: 2590
VitaMTP: cannot open usb
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44720343390780C80
Using protocol mode:  "automatic"
Sending Qcma protocol version: 1900010
Identifying as "Flo-PC"
Starting event loop
Icon changed - connected
Starting event_thread: 0x00000000000004e8
Sending new event
Event received in void CmaEvent::vitaEventGetSettingInfo(vita_event_t*, int), code: 0xc112, id: 11
Current account id: 7d70455523fc2540
Ended event, code: 0xc112, id: 11
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 12
Reading from local file
Sending 582 bytes of data for HTTP request http://fuk01.psp2.update.playstation.net/update/psp2/list/uk/psp2-updatelist.xml?ver=03520000&sid=64d3b1cf5c9b2d2834ef8e98565e29d6101c197ffae56bb65f23940c981f7bb1&nd=0
Ended event, code: 0xc10b, id: 12

**Comment by codestation** [comment]
Your region seems to be *uk*. Probably your xml file has some problem, you could try using the original one (download the xml from the http link in your log) or use the one attached in this comment (i already edited it for match your region).
[psp2-updatelist.xml.zip](https://github.com/codestation/qcma/files/416363/psp2-updatelist.xml.zip)

**Comment by Jamakusi** [comment]
I dont know why my systhem was located in the uk but it worked ( bought it here in germany ^^) 
Thanks for the help :)

**Comment by chronoss09** [comment]
this theat is great, my vita is now an 3.60, thanks alot Codestation and Jumakusi for this threat ;)

**Comment by chaos16vampy** [comment]
i have the same problem 
C:\Program Files\Qcma>qcma_console.exe --verbose
Starting Qcma 0.3.13
Current locale: "es_CL"
Starting main thread: 0x0000000000002570
Starting cma threads
Starting usb_thread: 0x0000000000001b18
Using protocol mode:  "manual"
Starting wireless_thread: 0x00000000000015d4
Starting database_thread: 0x0000000000000a10
Waiting for wireless connection
VitaMTP: waiting for connection
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 03274167620106005
Using protocol mode:  "manual"
Sending Qcma protocol version: 1900010
Identifying as "vampy-note2"
Starting event loop
Icon changed - connected
Starting event_thread: 0x0000000000001598
Sending new event
Event received in void CmaEvent::vitaEventGetSettingInfo(vita_event_t*, int), code: 0xc112, id: 6
Current account id: 8ca7b54a17649e55
Ended event, code: 0xc112, id: 6
Added objects for OHFI 0x01: 45
Added objects for OHFI 0x02: 570
Added objects for OHFI 0x03: 3
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 0
Added objects for OHFI 0x0A: 0
Added objects for OHFI 0x0D: 0
Added objects for OHFI 0x0E: 52
Added objects for OHFI 0x10: 0
Added objects for OHFI 0x12: 0
Total entries added to the database: 670
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 7
Reading from local file
Sending 588 bytes of data for HTTP request http://fmx01.psp2.update.playstation.net/update/psp2/list/mx/psp2-updatelist.xml?ver=03500000&sid=e88d79a1f2f30c356bb134c7671dc3be5b96c1202ad6fea5093771678f121d6c&nd=0
Ended event, code: 0xc10b, id: 7
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 8
Reading from local file
Sending 588 bytes of data for HTTP request http://fmx01.psp2.update.playstation.net/update/psp2/list/mx/psp2-updatelist.xml?ver=03500000&sid=e88d79a1f2f30c356bb134c7671dc3be5b96c1202ad6fea5093771678f121d6c&nd=0
Ended event, code: 0xc10b, id: 8

**Comment by codestation** [comment]
The region on your XML file is wrong, download the one from my attachment and replace `<region id="uk">` with `<region id="mx">`

**Comment by Amara76** [comment]
Hello 
Having a problem with my Ps vita, error ( C0-10139-4), i've change the region " uk", "us", "eu", "jap". 

I've the logs with QCMA in verbose : 

C:\Program Files\Qcma>qcma_console.exe --verbose
Starting Qcma 0.3.13
Current locale: "fr_FR"
Starting main thread: 0x0000000000000ae0
Starting cma threads
Starting usb_thread: 0x00000000000008ac
Using protocol mode:  "automatic"
Starting wireless_thread: 0x0000000000000bf8
Waiting for wireless connection
Starting database_thread: 0x0000000000000b24
VitaMTP: waiting for connection
Added objects for OHFI 0x01: 0
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 41742210358750BC0
Using protocol mode:  "automatic"
Sending Qcma protocol version: 1900010
Identifying as "USEREDD4"
Starting event loop
Icon changed - connected
Starting event_thread: 0x00000000000004dc
Added objects for OHFI 0x02: 130
Added objects for OHFI 0x03: 0
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 0
Added objects for OHFI 0x0A: 0
Added objects for OHFI 0x0D: 0
Added objects for OHFI 0x0E: 0
Added objects for OHFI 0x10: 0
Added objects for OHFI 0x12: 0
Total entries added to the database: 130

Can you help me please ? 
Thanks !

**Comment by VinyLimaZ** [comment]
Stoping asking this guys, please, here its a social program platform...
If you don't have the expertise to realize that the code you have to put in the xml its on the url that appear on --verbose
`http://fmx01.psp2.update.playstation.net/update/psp2/list/**mx**/psp2-updatelist.xml?ver=03500000&sid=e88d79a1f2f30c356bb134c7671dc3be5b96c1202ad6fea5093771678f121d6c&nd=0`
`http://fuk01.psp2.update.playstation.net/update/psp2/list/**uk**/psp2-updatelist.xml?ver=03520000&sid=64d3b1cf5c9b2d2834ef8e98565e29d6101c197ffae56bb65f23940c981f7bb1&nd=0`
You're more dumb than sony, that didnt put that automatic...

**Comment by codestation** [comment]
The latest Qcma handles both the region code and firmware version on the generated xml that is sent to the vita. In fact, any xml put in the updates folder is now ignored to prevent more reports like these.

**Comment by yamseng** [comment]
I need help, qcma crash after my psv show new updates as 3.63

C:\Program Files\Qcma>qcma_console.exe --verbose
Starting Qcma v0.4.1
Current locale: "en_MY"
Cannot load translation for locale: "en_MY"
Starting main thread: 0x0000000000001298
Starting cma threads
Starting usb_thread: 0x0000000000001084
Using protocol mode:  "automatic"
Starting database_thread: 0x000000000000172c
Starting wireless_thread: 0x0000000000001634
Waiting for wireless connection
VitaMTP: waiting for connection
PTP: Opening session
VitaMTP: Cannot read device name, device on standby
**[png @ 0000000003515d20] Invalid PNG signature 0xD4948445200.**
Added objects for OHFI 0x01: 163
Added objects for OHFI 0x02: 25
Added objects for OHFI 0x03: 0
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 0
Added objects for OHFI 0x0A: 0
Added objects for OHFI 0x0D: 0
Added objects for OHFI 0x0E: 0
Added objects for OHFI 0x10: 0
Added objects for OHFI 0x12: 0
Total entries added to the database: 188
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
VitaMTP: cannot open usb
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44713850399450C61
Using protocol mode:  "automatic"
Sending Qcma protocol version: 1900010
Identifying as "GanYenSeng-PC"
Starting event loop
Icon changed - connected
Starting event_thread: 0x000000000000098c
Sending new event
Event received in void CmaEvent::vitaEventGetSettingInfo(vita_event_t*, int), co
de: 0xc112, id: 23
Current account id: 0b8f58e910885428
Ended event, code: 0xc112, id: 23
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, i
nt), code: 0xc10b, id: 24
URL: http://fsa01.psp2.update.playstation.net/update/psp2/list/sa/psp2-updatelis
t.xml?ver=03520000&sid=7ee6f056c4f4634cfbadd138fd51ce2704cf11610fabdcefa42667d9f
5fb7fe7&nd=0
Starting http_thread: 0x0000000000000e80
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
remote download complete
Sending 1102 bytes of data for HTTP request http://fsa01.psp2.update.playstation
.net/update/psp2/list/sa/psp2-updatelist.xml?ver=03520000&sid=7ee6f056c4f4634cfb
add138fd51ce2704cf11610fabdcefa42667d9f5fb7fe7&nd=0
sending data:  1012 , left in buffer:  90
sending data:  90 , left in buffer:  0

**Comment by reed280** [comment]
> Are you trying to install a manual update by the "Update by Connecting to a PC]"? Instead of running qcma.exe do the following:
> 
> Open cmd and run the following commands:
> 
> ```
> cd %PROGRAMFILES%\Qcma
> qcma_console.exe --verbose
> ```
> Try to update until you get the error, close qcma and paste the log here.

Can You help me too?? please ? im having a problem in updating my ps vita i have the same problem on this discussion 

C:\Program Files\Qcma>qcma_console.exe --verbose
Starting Qcma v0.4.1
Current locale: "en_US"
Cannot load translation for locale: "en_US"
Starting main thread: 0x000000000001f708
Starting cma threads
Starting usb_thread: 0x000000000001f0a8
Using protocol mode:  "automatic"
Starting wireless_thread: 0x0000000000020758
Starting database_thread: 0x0000000000020350
PTP: Opening session
Waiting for wireless connection
Added objects for OHFI 0x01: 0
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44722258784020C92
Using protocol mode:  "automatic"
Sending Qcma protocol version: 1900010
Identifying as "Randory"
Starting event loop
Icon changed - connected
Starting event_thread: 0x000000000001ce00
Added objects for OHFI 0x02: 2504
Added objects for OHFI 0x03: 0
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 0
Added objects for OHFI 0x0A: 37
Added objects for OHFI 0x0D: 0
Added objects for OHFI 0x0E: 14
Added objects for OHFI 0x10: 0
Added objects for OHFI 0x12: 0
Total entries added to the database: 2555
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 1
Reading from local file
Sending 811 bytes of data for HTTP request http://fuk01.psp2.update.playstation.net/update/psp2/list/uk/psp2-updatelist.xml?ver=03650000&sid=e722e14462cffe6b8cf9cc1dd549f77c1b6fa2b18f630bdeac38a059389ab1c5&nd=0
Ended event, code: 0xc10b, id: 1
VitaMTP: waiting for connection

**Comment by tolipschris** [comment]
> 
> 
> > Are you trying to install a manual update by the "Update by Connecting to a PC]"? Instead of running qcma.exe do the following:
> > Open cmd and run the following commands:
> > ```
> > cd %PROGRAMFILES%\Qcma
> > qcma_console.exe --verbose
> > ```
> > 
> > 
> > Try to update until you get the error, close qcma and paste the log here.
> 
> Can You help me too?? please ? im having a problem in updating my ps vita i have the same problem on this discussion
> 
> C:\Program Files\Qcma>qcma_console.exe --verbose
> Starting Qcma v0.4.1
> Current locale: "en_US"
> Cannot load translation for locale: "en_US"
> Starting main thread: 0x000000000001f708
> Starting cma threads
> Starting usb_thread: 0x000000000001f0a8
> Using protocol mode: "automatic"
> Starting wireless_thread: 0x0000000000020758
> Starting database_thread: 0x0000000000020350
> PTP: Opening session
> Waiting for wireless connection
> Added objects for OHFI 0x01: 0
> VitaMTP: Detected device name: PlayStation(R)Vita
> Starting new USB connection
> Vita connected, id: 44722258784020C92
> Using protocol mode: "automatic"
> Sending Qcma protocol version: 1900010
> Identifying as "Randory"
> Starting event loop
> Icon changed - connected
> Starting event_thread: 0x000000000001ce00
> Added objects for OHFI 0x02: 2504
> Added objects for OHFI 0x03: 0
> Added objects for OHFI 0x05: 0
> Added objects for OHFI 0x06: 0
> Added objects for OHFI 0x0A: 37
> Added objects for OHFI 0x0D: 0
> Added objects for OHFI 0x0E: 14
> Added objects for OHFI 0x10: 0
> Added objects for OHFI 0x12: 0
> Total entries added to the database: 2555
> Sending new event
> Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 1
> Reading from local file
> Sending 811 bytes of data for HTTP request http://fuk01.psp2.update.playstation.net/update/psp2/list/uk/psp2-updatelist.xml?ver=03650000&sid=e722e14462cffe6b8cf9cc1dd549f77c1b6fa2b18f630bdeac38a059389ab1c5&nd=0
> Ended event, code: 0xc10b, id: 1
> VitaMTP: waiting for connection

**Comment by tolipschris** [comment]
Having an issue when i try to update.
C0-10139-4
Only thing i could found on the internet was that it has something to do with the region (not confirmed) but i tried every region now and it failed every time

**Comment by tolipschris** [comment]
Having an issue when i try to update.
C0-10139-4
Only thing i could found on the internet was that it has something to do with the region (not confirmed) but i tried every region now and it failed every time

**Comment by codestation** [comment]
Are you using a custom XML? delete it and use the Qcma settings instead to set an specific version.

Sorry, i don't have a PSVita anymore so is difficult to continue giving support on it.

**Comment by alexbmc1** [comment]
dude please i need help 

aparently the ps was bought from japan and used in europe and the log says us
Starting Qcma v0.4.1
Current locale: "en_US"
Cannot load translation for locale: "en_US"
Starting main thread: 0x00000000000023e0
Starting cma threads
Starting usb_thread: 0x0000000000000fb0
Using protocol mode:  "automatic"
Starting wireless_thread: 0x0000000000001320
Starting database_thread: 0x00000000000018e8
Waiting for wireless connection
PTP: Opening session
Added objects for OHFI 0x01: 0
VitaMTP: waiting for connection
Added objects for OHFI 0x02: 0
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44718467068000C80
Using protocol mode:  "automatic"
Sending Qcma protocol version: 1900010
Identifying as "DESKTOP-7U8TFHR"
Starting event loop
Icon changed - connected
Starting event_thread: 0x00000000000017e8
Added objects for OHFI 0x03: 1
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 0
Added objects for OHFI 0x0A: 0
Added objects for OHFI 0x0D: 0
Added objects for OHFI 0x0E: 0
Added objects for OHFI 0x10: 0
Added objects for OHFI 0x12: 0
Total entries added to the database: 1

**Comment by alexbmc1** [comment]
> Are you using a custom XML? delete it and use the Qcma settings instead to set an specific version.
> 
> Sorry, i don't have a PSVita anymore so is difficult to continue giving support on it.
dude please i need help

aparently the ps was bought from japan and used in europe and the log says us
Starting Qcma v0.4.1
Current locale: "en_US"
Cannot load translation for locale: "en_US"
Starting main thread: 0x00000000000023e0
Starting cma threads
Starting usb_thread: 0x0000000000000fb0
Using protocol mode: "automatic"
Starting wireless_thread: 0x0000000000001320
Starting database_thread: 0x00000000000018e8
Waiting for wireless connection
PTP: Opening session
Added objects for OHFI 0x01: 0
VitaMTP: waiting for connection
Added objects for OHFI 0x02: 0
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44718467068000C80
Using protocol mode: "automatic"
Sending Qcma protocol version: 1900010
Identifying as "DESKTOP-7U8TFHR"
Starting event loop
Icon changed - connected
Starting event_thread: 0x00000000000017e8
Added objects for OHFI 0x03: 1
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 0
Added objects for OHFI 0x0A: 0
Added objects for OHFI 0x0D: 0
Added objects for OHFI 0x0E: 0
Added objects for OHFI 0x10: 0
Added objects for OHFI 0x12: 0
Total entries added to the database: 1

**Comment by monkamelvis** [comment]
Hi please help me. my ps vita wont load up.

C:\Program Files\Qcma>qcma_console.exe --verbose
Starting Qcma v0.4.1
Current locale: "en_GB"
Cannot load translation for locale: "en_GB"
Starting main thread: 0x0000000000006b24
Starting cma threads
Starting usb_thread: 0x0000000000002454
Using protocol mode:  "custom"
Starting database_thread: 0x0000000000006988
Starting wireless_thread: 0x00000000000004a4
Waiting for wireless connection
VitaMTP: waiting for connection
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44722259538490C92
Using protocol mode:  "custom"
Sending Qcma protocol version: 1900010
Identifying as "home"
Starting event loop
Starting event_thread: 0x0000000000006010
Icon changed - connected
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 31
Reading from local file
Sending 810 bytes of data for HTTP request http://fuk01.psp2.update.playstation.net/update/psp2/list/uk/psp2-updatelist.xml?ver=03720000&sid=9e49caa0f14ad3203076675c3b6c767abbc2e51f24ea476732da60b9960b7525&nd=0
Ended event, code: 0xc10b, id: 31
Added objects for OHFI 0x01: 47
Added objects for OHFI 0x02: 10264
Added objects for OHFI 0x03: 0
Added objects for OHFI 0x05: 0
Added objects for OHFI 0x06: 2
Added objects for OHFI 0x0A: 10
Added objects for OHFI 0x0D: 6
Added objects for OHFI 0x0E: 0
Added objects for OHFI 0x10: 2
Added objects for OHFI 0x12: 2
Total entries added to the database: 10333
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 31
Sending new event
Failed to receive URL
Ended event, code: 0xc10b, id: 31
Unknown event not handled, code: 0x0, id: 0
Sending new event
Param1: 0x00000000, Param2: 0x001C6E48, Param3: 0x00000000
Ended event, code: 0x0, id: 0
Unknown event not handled, code: 0x0, id: 0
VitaMTP: PTP: reading event an error 0x02ff occurred
Error reading event from Vita.
Param1: 0x00000000, Param2: 0x00000010, Param3: 0xC10B0004
Ended event, code: 0x0, id: 0
Finishing event_thread
Finishing event loop
Releasing device...
VitaMTP: ERROR: Could not close session!
Icon changed - disconnected
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44722259538490C92
Using protocol mode:  "custom"
Sending Qcma protocol version: 1900010
Identifying as "home"
Starting event loop
Icon changed - connected
Starting event_thread: 0x00000000000068cc
Sending new event
Unknown event not handled, code: 0xffff, id: 0
Sending new event
Param1: 0x00000000, Param2: 0x846CB1B0, Param3: 0xFFFFC08B
Ended event, code: 0xffff, id: 0
Unknown event not handled, code: 0xffff, id: -16245
Sending new event
Param1: 0xFFFFC08B, Param2: 0x00000000, Param3: 0x00000000
Ended event, code: 0xffff, id: -16245
Unknown event not handled, code: 0x0, id: 0
Sending new event
Param1: 0x00000000, Param2: 0x8653E4C0, Param3: 0xFFFFC08B
Ended event, code: 0x0, id: 0
Unknown event not handled, code: 0x0, id: -16245
Sending new event
Param1: 0xFFFFC08B, Param2: 0x846CB1B0, Param3: 0xFFFFC08B
Ended event, code: 0x0, id: -16245
Unknown event not handled, code: 0xffff, id: 0
VitaMTP: PTP: reading event an error 0x02ff occurred
Param1: 0x00000000, Param2: 0x00000000, Param3: 0x00000000
Error reading event from Vita.
Ended event, code: 0xffff, id: 0
Finishing event_thread
Finishing event loop
Releasing device...
VitaMTP: ERROR: Could not close session!
Icon changed - disconnected
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44722259538490C92
Using protocol mode:  "custom"
Sending Qcma protocol version: 1900010
Identifying as "home"
Starting event loop
Icon changed - connected
Sending new event
Starting event_thread: 0x0000000000002188
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 32
Reading from local file
Sending 810 bytes of data for HTTP request http://fuk01.psp2.update.playstation.net/update/psp2/list/uk/psp2-updatelist.xml?ver=03720000&sid=9e49caa0f14ad3203076675c3b6c767abbc2e51f24ea476732da60b9960b7525&nd=0
Ended event, code: 0xc10b, id: 32
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 32
Sending new event
Failed to receive URL
Ended event, code: 0xc10b, id: 32
Unknown event not handled, code: 0x6d, id: 6029422
Sending new event
Param1: 0x005C006E, Param2: 0x00440041, Param3: 0x005C0053
Ended event, code: 0x6d, id: 6029422
Unknown event not handled, code: 0x62, id: 6619204
Sending new event
Param1: 0x00650044, Param2: 0x00000010, Param3: 0xC10B0004
Ended event, code: 0x62, id: 6619204
Unknown event not handled, code: 0x0, id: 7340143
VitaMTP: PTP: reading event an error 0x02ff occurred
Param1: 0x0070006F, Param2: 0x00430020, Param3: 0x006D006F
Error reading event from Vita.
Ended event, code: 0x0, id: 7340143
Finishing event_thread
Finishing event loop
Releasing device...
VitaMTP: ERROR: Could not close session!
Icon changed - disconnected
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44722259538490C92
Using protocol mode:  "custom"
Sending Qcma protocol version: 1900010
Identifying as "home"
Starting event loop
Icon changed - connected
Starting event_thread: 0x0000000000005a3c
Sending new event
Unknown event not handled, code: 0x0, id: 0
Sending new event
Param1: 0x00000000, Param2: 0x00000020, Param3: 0x00000000
Ended event, code: 0x0, id: 0
Sending new event
Unknown event not handled, code: 0x0, id: 0
Param1: 0x00000000, Param2: 0x00000000, Param3: 0x00000000
Ended event, code: 0x0, id: 0
Unknown event not handled, code: 0x0, id: 2147483647
Sending new event
Param1: 0x7FFFFFFF, Param2: 0x00000010, Param3: 0x00000000
Ended event, code: 0x0, id: 2147483647
Unknown event not handled, code: 0x0, id: 0
Param1: 0x00000000, Param2: 0x00000010, Param3: 0x00000000
Ended event, code: 0x0, id: 0
VitaMTP: PTP: reading event an error 0x02ff occurred
Error reading event from Vita.
Finishing event_thread
Finishing event loop
Releasing device...
VitaMTP: ERROR: Could not close session!
Icon changed - disconnected
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 44722259538490C92
Using protocol mode:  "custom"
Sending Qcma protocol version: 1900010
Identifying as "home"
Starting event loop
Icon changed - connected
Starting event_thread: 0x0000000000006780

**Comment by Yolomation** [comment]
hello! i pretty much made an account here just to fix my soft blocked vita. ive tried using every method here and im pretty new to this xml stuff. If you could respond it would be much appreciated!
