### ISSUE TITLE
QCMA won't connect to PS Vita OFW 1.06

### ISSUE THREAD

**Issue by zurez** [codestation/qcma#55]
`Starting Qcma 0.3.12
Current locale: "en_IN"
Cannot load translation for locale: "en_IN"
Starting main thread: 0x00007fd8d8ee1900
Current desktop:  "Unity"
Cannot load libqcma_appindicator plugin from "/usr/lib/qcma"
Starting cma threads
Starting usb_thread: 0x00007fd8c671e700
Using protocol mode:  "manual"
PTP: Opening session
Starting wireless_thread: 0x00007fd8af7fe700
Waiting for wireless connection
VitaMTP: waiting for connection
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 03274174220264801
Using protocol mode:  "manual"
Sending Qcma protocol version: 1000010
Identifying as "EmptyBox"
Starting event loop
Starting event_thread: 0x00007fd8aedeb700
Icon changed - connected
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 2
Reading from local file
Sending 582 bytes of data for HTTP request http://feu01.psp2.update.playstation.net/update/psp2/list/eu/psp2-updatelist.xml
Ended event, code: 0xc10b, id: 2
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 3
Reading from local file
Sending 752 bytes of data for HTTP request http://feu01.psp2.update.playstation.net/update/psp2/list/eu/psp2-updatelist.xml
Ended event, code: 0xc10b, id: 3

`
I am trying to connect , but I am always getting "Connect through a usb cable issue"
I have seen other user on firmware having this issue.

**Comment by codestation** [comment]
According with the log line

`Reading from local file`

Qcma is sending the updatelist file from a local file in your update folder. Maybe that file is malformed (missing your region (eu) for example). Have you tried to remove it first?

**Comment by zurez** [comment]
If I remove the file , then qcma starts reading from cache. Is there any way for me to clear the cache?
Also I got the xml file from the soluton you posted for Issue 53.
Attaching a copy. My PsVita is 1004 series, so definitey EU region.
[psp2-updatelist.xml.tar.gz](https://github.com/codestation/qcma/files/452912/psp2-updatelist.xml.tar.gz)

**Comment by zurez** [comment]
And really thank you for replying. As a fellow dev, I know how hard it is to maintain a repo.

**Comment by codestation** [comment]
If no file is present then qcma will serve this file instead: https://github.com/codestation/qcma/blob/master/common/resources/xml/psp2-updatelist.xml
but before sending it it will modify the region value to match the one in the request url.

Just for the record, it you put the file from http://feu01.psp2.update.playstation.net/update/psp2/list/eu/psp2-updatelist.xml it will prompt for an update?

If you put the same file but with the version number to `01.060.000` it disconnects too?

Just want to see if there is a problem with the embedded xml file.

**Comment by zurez** [comment]
I copied and pasted  from 
 http://feu01.psp2.update.playstation.net/update/psp2/list/eu/psp2-updatelist.xml
Same issue.
Where do you want me to change the version numbers ?

**Comment by codestation** [comment]
So by using the original file it still disconnects? Have you tried with an higher protocol version (like 1.50)? The FW 1.00 protocol number (1000010) has never been tested, is assumed that older than 1.50 use this value but i cannot verify that.

If the offline mode is unchecked it still fails?

**Comment by zurez** [comment]
*This happens when CMA protocol is latest and offline mode is unchecked
**************************************
Starting Qcma 0.3.12
Current locale: "en_IN"
Cannot load translation for locale: "en_IN"
Starting main thread: 0x00007f289f000900
Current desktop:  "Unity"
Cannot load libqcma_appindicator plugin from "/usr/lib/qcma"
Starting cma threads
Starting usb_thread: 0x00007f2890853700
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 03274174220264801
Using protocol mode:  "automatic"
Sending Qcma protocol version: 1900010
Identifying as "EmptyBox"
Starting event loop
Starting event_thread: 0x00007f2881857700
Icon changed - connected
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 1
Found request for update list. Sending cached data
Detected country code from URL:  "eu"
Sending 572 bytes of data for HTTP request http://feu01.psp2.update.playstation.net/update/psp2/list/eu/psp2-updatelist.xml
Ended event, code: 0xc10b, id: 1
^C
zurez@EmptyBox:~$ 
zurez@EmptyBox:~$ qcma --verbose
Starting Qcma 0.3.12
Current locale: "en_IN"
Cannot load translation for locale: "en_IN"
Starting main thread: 0x00007efcfb4d0900
Current desktop:  "Unity"
Cannot load libqcma_appindicator plugin from "/usr/lib/qcma"
Starting cma threads
Starting usb_thread: 0x00007efcdffff700
PTP: Opening session
VitaMTP: Detected device name: PlayStation(R)Vita
Starting new USB connection
Vita connected, id: 03274174220264801
Using protocol mode:  "automatic"
Sending Qcma protocol version: 1900010
Identifying as "EmptyBox"
Starting event loop
Icon changed - connected
Starting event_thread: 0x00007efcddd04700
Sending new event
Event received in void CmaEvent::vitaEventSendHttpObjectFromURL(vita_event_t*, int), code: 0xc10b, id: 2
URL: http://feu01.psp2.update.playstation.net/update/psp2/list/eu/psp2-updatelist.xml
Starting http_thread: 0x00007efcdd503700
Sending 1102 bytes of data for HTTP request http://feu01.psp2.update.playstation.net/update/psp2/list/eu/psp2-updatelist.xml
remote download complete
sending data:  1012 , left in buffer:  90
sending data:  90 , left in buffer:  0
Ended event, code: 0xc10b, id: 2


**************************************

**Comment by zurez** [comment]
Changing protocol to 1.50 or 1.60 , gives the same error

**Comment by zurez** [comment]
The  error remains if I change protocol to 1.60 and uncheck offline.

**Comment by codestation** [comment]
Can you post the output of qcma --with-debug? if is too large use pastebin or similar.

**Comment by zurez** [comment]
Here is the pastebin link.
3 times tried to update.
One time disconnected and re connected
http://pastebin.com/vibFdqXK

**Comment by zurez** [comment]
How do I check libvitamtp version?
I installed through terminal. Didn't build it.

**Comment by zurez** [comment]
I think it's libvitamtp5_2.5.9
Doing a "locate libvitamtp" gave me the result.
Has OpenCMA ever broken backward compatibility?

**Comment by codestation** [comment]
Not since i started warking on Qcma. BTW, is your vita activated (doesn't matter if is currently logged out)? I noticed from your logs that your vita  doesn't send the account info nor query for capabilities before requesting an update. As far as i know even the official CMA refuses to work if the vita doesn't have any account on it. Thats the only thing i noticed out of the ordinary.

**Comment by zurez** [comment]
No the vita is not activated. Its tough to activate vita at 1.06 . I planned to update first and then activate.

**Comment by codestation** [comment]
Seems that your options are:

* Activate with a PS3.
* See if OpenCMA works then inject the 3.60 PUP using charles proxy.

Cannot debug this more since i don't have a non-activated vita and cannot deactivate mine since i don't have a PS3 to reactivate it (i m not on latest firmware).

**Comment by zurez** [comment]
If I try to update using a Vita Game Memory Card or through the recovery console , I will still need the account information?
I am also not able to add PSN details. Apparently things don't work on 1.06

**Comment by zurez** [comment]
Managed to solve the update issue (without using qcma). Activated and connected to PSN.
I will test if QCMA is able to connect now

**Comment by zurez** [comment]
Still not able to connect

**Comment by zurez** [comment]
Fixed.
Formatted Memory Card
Restored System.
Working for me now.
