### ISSUE TITLE
cant connect 

### ISSUE THREAD

**Issue by blackleaf420** [codestation/qcma#56]
my psn nickname pops up on my pc but my vita returns error c0-112644-4 everytime

**Comment by codestation** [comment]
Can you give me more info?

* What OS?
* Qcma version.
* If using Linux, vitamtp version.
* Current firmware on your PSVita.
* CMA protocol settings (last 3 options, check qcma settings).
* If possible a log (run qcma --verbose, or qcma_console.exe --verbose on windows).

**Comment by blackleaf420** [comment]
os=windows 10

qcma=3.12

vita=3.36
 
latest protocol

**Comment by codestation** [comment]
What driver are you using? Can you try with libusb0? Go to `C:\Program FIles\Qcma\driver` and install `QcmaDriver_libusb0.exe` (or re-run the installer and check libusb0 from the install menu).
