### ISSUE TITLE
VITA DUMPS GAMES SAVEDATA DELETED

### ISSUE THREAD

**Issue by klinux86** [codestation/qcma#58]
Hi guys,

I would like to thank you for the hard work done on qcma.

I want to inform you that the new vita dumps savedata is deleted after saving the game on pc and restore it by qcma.

Can you please correct this bug.

Best regards

klinux

**Comment by codestation** [comment]
Dumps? if you are talking about vitamin dumps then i cannot provide support for them since they are an unofficial way to store games on the vita and CMA way to backup them is unknown.

**Comment by klinux86** [comment]
Hi,

First I would like to hank you for your support, after investigation it
seems that the problem was related to henkaku not for qcma.
