### ISSUE TITLE
QCMA 0.3.12-2 Crashes due to missing framework on OSX 10.10.5

### ISSUE THREAD

**Issue by ccfman2004** [codestation/qcma#59]
When I try to run the 0.3.12-2 version I get a crash with the following error:

`Dyld Error Message:
  Symbol not found: _kCVImageBufferColorPrimaries_ITU_R_2020

  Referenced from: /Applications/Qcma.app/Contents/MacOS/../Frameworks/libavcodec.57.dylib (which was built for Mac OS X 10.11)

  Expected in: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
 in /Applications/Qcma.app/Contents/MacOS/../Frameworks/libavcodec.57.dylib`

Is it because I am running Mac OS X 10.10.5?

Version 0.3.12 ran fine on Mac OS X 10.10.5 as long as I wasn't in Henkaku mode.

**Comment by codestation** [comment]
Will try to use a ffmpeg version compiled with a previous OSX version to see if it fixes the problem.

**Comment by ccfman2004** [comment]
I don't use ffmpeg.

**Comment by codestation** [comment]
Sorry, it means that i wil try to use a ffmpeg version compiled with a previous OSX version to see if it fixes the problem.

On the current qcma version i just bundle the ffmpeg libraries that come from `brew install ffmpeg`. Looks like that those aren't compatible with previous OSX versions anymore.

**Comment by theinvisiblehand** [comment]
I'm having the same issue is there a fix?

**Comment by phant0mg33k** [comment]
Yeah having the same issue. Running brew to install ffmpeg has not changed the issue. Any chance a roll back might help?

**Comment by codestation** [comment]
I am uploading a preview version without ffmpeg so it can run on previous macOS versions. Of course there isn't image or video previews with this one but all the other functions are working the same.

http://codestation.nekmo.com/qcma/0.3.13/macos/

Any confirmation that this one works on previous OSX versions (not "El Capitan" or "Sierra") is appreciated.

**Comment by ccfman2004** [comment]
Seems to work for me.  10.10.5

**Comment by diabolicfutility** [comment]
The version without FFMPEG now works for me.

**Comment by codestation** [comment]
0.4.0 is released for macOS, i will now provide two versions (the one without ffmpeg should work on older OS versions).

https://github.com/codestation/qcma/releases/tag/v0.4.0

**Comment by arroadie** [comment]
The version you provided on this link still crashes on yosemite
```shell
➜  ~ /Applications/Qcma.app/Contents/MacOS/qcma
dyld: Symbol not found: _kCVImageBufferColorPrimaries_ITU_R_2020
  Referenced from: /Applications/Qcma.app/Contents/MacOS/../Frameworks/libavcodec.57.dylib (which was built for Mac OS X 10.12)
  Expected in: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
 in /Applications/Qcma.app/Contents/MacOS/../Frameworks/libavcodec.57.dylib
[1]    51564 trace trap  /Applications/Qcma.app/Contents/MacOS/qcma
```

**Comment by arroadie** [comment]
quick update:
replacing the version you provided on the app with the version brew compiles on my machine fixes the issue
