### ISSUE TITLE
ADD a translation？

### ISSUE THREAD

**Issue by jatalin** [codestation/qcma#60]
Hallo，
I find three language translations at resources like Spanish，French and Japanese 
https://github.com/codestation/qcma/tree/master/common/resources/translations

If I Update a Chinese translation,Can you add it at QCMA 3.14？

**Comment by codestation** [comment]
Yes, just use the Qt linguist app to generate the language file.

**Comment by codestation** [comment]
Closed by inactivity, feel free to provide a PR with the chinese translation.
