### ISSUE TITLE
Extremely unstable software

### ISSUE THREAD

**Issue by psvita123** [codestation/qcma#61]

**Comment by psvita123** [comment]
Hello code station
I have a big issue with qcma
It seems it doe not like my PC.
The whole issue is with the drivers.
What I have done : 
1 - install lilusb0 driver
PS vita not detected
2 -  disable firewall
Ps vita not detected
3 - install lilusbk driver (from ur software not zidiag)
PS vita not detected
There is some detail here.
After installing this driver I went to device manager over there it was showing error with the PS vita tube b driver .
The error is.   
Windows cannot load the device driver for this hardware. The driver may be corrupted or missing. (Code 39)
Object Name not found.
I tried reinstalling the driver but no luck
4 - install lilusbk driver from source forge (something like that)
Over here the first time I connect my vita it connects properly but afterwards when I piut my vita on sleep and then want to reconnect again not detected.
Installing this driver also cannot let me uninstall qcma, can't restart my pc, I guess becuz qcma.exe is always running.
5 - install winusb driver
PS vita not detected

I'm running PS vita 3.60 with henkaku
Pls help me.

**Comment by codestation** [comment]
What is your windows version? Try to reboot between driver installations, generally only the first installation will not need to reboot. Also you can change driver without reinstalling Qcma, just go to `C:\Program FIles\Qcma\driver` and you will find the driver installers.

**Comment by psvita123** [comment]
i have windows 10 64 bit

**Comment by psvita123** [comment]
which driver should i install

**Comment by codestation** [comment]
I use a windows 10 64bit too as a test pc and these are my experience with different drivers:

* libusb0: always works for me.
* libusbk: fails to detect the first time but it works on next connection. Some people reports that doesn't work for them.
* winusb: haven't tested much yet (recently added) but it worked for me on the first try.

Make sure that the official CMA isn't running since it interferes with Qcma.

**Comment by codestation** [comment]
0.4.0 released. I tested with winusb/libusb0 and seems to work properly on windows.

https://github.com/codestation/qcma/releases/tag/v0.4.0

**Comment by psvita123** [comment]
Thanks alot for your hard work.
I will test it out.....
