### ISSUE TITLE
Install VPK using QCMA [FEATURE REQUEST]

### ISSUE THREAD

**Issue by zurez** [codestation/qcma#64]
Feature Request.
Will it be possible to install vpks using qcma? We already have vpk install over ftp using vitaorganizer but it is very slow.

**Comment by Kyogre** [comment]
codestation, is it realizable via PSP savegame restore?

**Comment by codestation** [comment]
Until we have control of CMA from the Vita side then directly installing vpk isn't possible. Technically if a homebrew that uses SceMtp api is made then it could be possible, but currently there is no documentation of efforts to reverse it.
