### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by Boucho11** [codestation/qcma#65]
Hi, I've been looking for the XML code though it doesn't seem to be here any more?

**Comment by codestation** [comment]
Not sure what do you mean..

XML file? https://github.com/codestation/qcma/blob/master/common/resources/xml/psp2-updatelist.xml

XML related code? https://github.com/codestation/qcma/blob/master/common/cmaevent.cpp#L538

**Comment by mashukouhai** [comment]
@codestation can You upload the original 'psp2-updatelist.xml' files 
The complete one with 84 line Without Cut Please
The 1st one you upload 
Thanks In advance Waiting ....

**Comment by codestation** [comment]
Do you mean this one? https://github.com/codestation/qcma/blob/9f790dc788841b4d459c2d53e5b20687b67cf84a/common/resources/xml/psp2-updatelist.xml

Note that this xml is missing some less known regions, thats why i ended generating the xml on the fly.

**Comment by codestation** [comment]
Closed as it has 7 days of inactivity. Also i am currently adding support for xml version change on the fly so providing your own xml file won't be neccesary anymore.
