### ISSUE TITLE
Music damaged file

### ISSUE THREAD

**Issue by illuminati2save** [codestation/qcma#66]
Hi, I recently Updated from 3.52 to the last firmware (3.61). But when I try to send music from the PC to PSVita, the music app of the psvita says me is a damaged file. I tried with converting the music (mp3 to mp3) with ffmpeg, vlc but nothing.
I use the qcma client of Linux installed from aur.
With the official cma I can send the music without any problem.

**Comment by codestation** [comment]
Cannot reproduce on my end. Are you using USB or WiFi to transfer the file? Are you copying the file or streaming it?

**Comment by illuminati69** [comment]
I tried to copy the file from USB.
