### ISSUE TITLE
Is there Downgrade i update My system 3.61 to 3.60

### ISSUE THREAD

**Issue by mashukouhai** [codestation/qcma#69]
<?xml version="1.0" encoding="UTF-8"?>
<update_data_list>
<region id="us">
    <np level0_system_version="00.000.000" level1_system_version="00.000.000" level2_system_version="00.000.000" map="00.000.000" />
    <np_d level0_system_version="00.000.000" level1_system_version="00.000.000" level2_system_version="00.000.000" map="00.000.000" />
    <version system_version="00.000.000" label="0.00">
      <update_data update_type="full">
        <image size="0">http://www.example.com/PSP2UPDAT.PUP</image>
      </update_data>
    </version>
</region>
</update_data_list>

**Comment by mashukouhai** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<update_data_list>
<region id="us">
    <np level0_system_version="00.000.000" level1_system_version="00.000.000" level2_system_version="00.000.000" map="00.000.000" />
    <np_d level0_system_version="00.000.000" level1_system_version="00.000.000" level2_system_version="00.000.000" map="00.000.000" />
    <version system_version="00.000.000" label="0.00">
      <update_data update_type="full">
        <image size="0">http://www.example.com/PSP2UPDAT.PUP</image>
      </update_data>
    </version>
</region>
</update_data_list>

**Comment by codestation** [comment]
No, at this moment there is no downgrade to 3.60. You can use a 3.60 xml and PUP but the vita will abort the installation before trying to do the update.
