### ISSUE TITLE
When transferring homebrew files using psp savedata, *.lnk files will be omitted.

### ISSUE THREAD

**Issue by jessehardy** [codestation/qcma#70]
If the data contains a file with *.lnk extension, qcma will ignore it, and omit it in the upload.

To fix it, QListDB::recursiveScanRootDirectory should be changed a little.
`dir.entryInfoList(QDir::AllEntries | QDir::NoDotAndDotDot, QDir::Time);`
To
`dir.entryInfoList(QDir::AllEntries | QDir::NoDotAndDotDot | QDir::System, QDir::Time);`

**Comment by codestation** [comment]
Any reason to allow lnk files? These are only used on windows by explorer.exe as a shortcut so they won't be followed by Qcma anyway. Also adding QDir::System would list sockets and device files on Linux.
