### ISSUE TITLE
Latest version build for window link is broken

### ISSUE THREAD

**Issue by quangnt** [codestation/qcma#71]
When click on download link in website for latest version, it broke. Can you fix the link

**Comment by codestation** [comment]
I just tested all the links and they are working properly.

[Qcma_setup_0.3.13-2.exe](http://codestation.nekmo.com/qcma/0.3.13/windows/Qcma_setup_0.3.13-2.exe)

**Comment by quangnt** [comment]
![image](https://cloud.githubusercontent.com/assets/899632/19708698/bcf1858a-9b4a-11e6-9907-4c0b50b516e5.png). Each time I clicked on download link, it display above image.

**Comment by quangnt** [comment]
Can you support me to upload it in another file sharing(ex: mediafire.com)?

**Comment by codestation** [comment]
There you go

https://mega.nz/#!lkIR1YjY!AmQ1fqGOZcE7e2lxKtb-i1jqvr6URRJYNfM_0a5BJQY

Also check your DNS settings, seems like that is the cause of your problem.

**Comment by quangnt** [comment]
thank you so much :) and your great work on this area :)
