### ISSUE TITLE
Qt5Cored.dll is missing at version Qcma_setup-0.4.0-1-g07915599

### ISSUE THREAD

**Issue by dragonflylee** [codestation/qcma#73]
0.40 windows version linked with the debug version of Qt, when i start up in Windows 10 Pro x64, it says Qt5Cored.dll is not found

**Comment by codestation** [comment]
Fixed on d1c873ade993b9feaebaf5e8b9166a1cea6b28c6

I will replace the windows installer on the next hour or so.
