### ISSUE TITLE
lilusb0.sys and lilusbk.sys missing

### ISSUE THREAD

**Issue by psvita123** [codestation/qcma#74]
Hello,
@codestation its me again remember i disturbed you a few months ago....
(if u dont remember me see this https://github.com/codestation/qcma/issues/610

Now again im here with an issue.....
i plugged my vita into pc and it was not recognized by the pc..
i though something went wrong with the drivers installed..
i uninstalled qcma and reinstalled it..
still no luck
now what i noticed Mr. @codestation was that there were not lilusb0.sys and lilusbk.sys in
over here......
C:\Windows\System32\drivers
where it was previously.....
i tried rebooting my pc and installing lilusb0, lilusbk, and winusb again using qcma .4 version
still those file were missing
then installed lilusb0 (and lilusbk0) using software from sourceforge..
now those file were present there but i encountered an old problem.
the pc only detected vita once then not again...
the same problem qcma.exe runs and runs 
have to pull the pc plug to turn it offf.
hope u will understand my problem......

**Comment by codestation** [comment]
You don't need to uninstall Qcma to change drivers, just go to `%PROGRAMFILES%\Qcma\driver` and you will find the driver installers in there.

Maybe try a different port? libusb has conflicts with USB 3.0 ports on some motherboards.

Have you tried to uninstall all the drivers, reboot then install only one? (libusb0 or winusb).

**Comment by psvita123** [comment]
No i dont have a pc with usb 3.0
What i feel strange that those files in drivers folders should not be
missing.
When i install qcma (after complete uninstall) those two files lilusb0.sys
and lilusbk.sys are not there in the driver folder as mentioned above.
Installation with the software on sourceforge places those file but are not
at all stable with qcma
Pls check on ur pc wheather those files are there or not?
Maybe a problem with qcma installer after update
Yes i did reboot my pc with only installation of driver but no luck

**Comment by codestation** [comment]
The drivers are stored in `C:\Windows\System32\drivers\DriverStore\FileRepository\ps_vita_type_b_blahblahblah\` (using libusb0 as an example) and copied to `C:\Windows\System32\drivers` (sys) and `C:\Windows\System32` (dll) when the PSVita is connected for the first time. If your vita isn't detected then you might have another problem.

Does your vita appear as `libusb-win32 Usb Devices -> PS Vita Type B` in the device manager when connected to the PC? (again, using libusb0 driver for the example).

**Comment by psvita123** [comment]
My vita appears as lilusbk
But there is small yellow sign with it
When i ri8 click it and go to properties this is the following text
Windows cannot load the device driver for this hardware. The driver may be
corrupted or missing. (Code 39)

Object Name not found.
I have tried reinstalling lilusb0 many times and everytime it shows
successful

**Comment by psvita123** [comment]
I even reinstalled lilusbk but no luck

**Comment by Tsegmid** [comment]
@psvita123 try zadig fix
https://komorebinomichi.wordpress.com/2015/06/04/how-to-use-qcma-with-usb-without-problems-in-windows/
