### ISSUE TITLE
Feature Request: Language Selector

### ISSUE THREAD

**Issue by internetakias** [codestation/qcma#75]
I'd like to see a language selector added to QCMA, since I've set my locale to Japanese to run various Japanese software but I'd like to QCMA to be in English without having to use a locale emulator.
Thanks in advance!

**Comment by codestation** [comment]
Just edit the Qcma shortcut and append ` --set-locale en` to the end of the command.

**Comment by internetakias** [comment]
Ah, thanks. Closing this.
