### ISSUE TITLE
Font size bug in Backup Manager

### ISSUE THREAD

**Issue by Kyogre** [codestation/qcma#76]
I have Windows 10 x64 + fullhd resolution + 150% scaling. I have this bug on every QCMA versions.

![qcma scaling bug](https://cloud.githubusercontent.com/assets/2260980/20650025/e9db0344-b4dd-11e6-93a9-b0bb85dcf2c1.png)

**Comment by codestation** [comment]
That is the only place where the problem happens? I am using CSS for that label, i would have to change it for something else so it scales with the rest of the GUI.

**Comment by Kyogre** [comment]
yes, the problem happens only for titles in all Backup Types
