### ISSUE TITLE
QCMA crashes after unplugging vita

### ISSUE THREAD

**Issue by Lapan** [codestation/qcma#77]
Pretty much every time i unplug the vita after transferring something it crashes QCMA

**Comment by codestation** [comment]
Sorry, i have been busy those weeks. What is your OS? 32 or 64 bits? What are you trying to copy? Can you attach a debug log? Just run qcma --with-debug (or qcma_console.exe --with-debug if you are on windows) and upload the log here.

**Comment by Lapan** [comment]
I use 64 bit Windows 7. 
If i unplug the vita without copying anything it works as normal, but if i copy images over first and then unplug it crashes pretty much every time. The copying itself works fine, the screenshots arrive in the correct folder.

[qcma_log.txt](https://github.com/codestation/qcma/files/644960/qcma_log.txt)
