### ISSUE TITLE
QCMA not working.

### ISSUE THREAD

**Issue by TheBorder** [codestation/qcma#80]
I can not do anything with the program as it disconnects after 30 sec.

here it is a video of it.  ( rename to .zip and extract it)

[video.pdf](https://github.com/codestation/qcma/files/644464/video.pdf)

**Comment by codestation** [comment]
Cannot reproduce your problem. Can you attach the folder that you are trying to copy? That windows is 32bit or 64bit?

Can you attach a log here? Open cmd and execute the following command (close qcma first):

```
"%PROGRAMFILES%\Qcma\qcma_console.exe" --with-debug > qcma_log.txt
```

Then connect your vita and do the same thing on the video. Once it disconnects close qcma and upload the log file. It will be located on `c:\users\your_user`

**Comment by TheBorder** [comment]
1. Its a mai dump cannot attach cause its 2 gb.
2. 64 bit
[qcma_log.txt](https://github.com/codestation/qcma/files/644579/qcma_log.txt)

**Comment by codestation** [comment]
Sorry, i forgot to add `2>&1` to the end of the command, can you try again?

**Comment by TheBorder** [comment]
and i was wondering cause the log had only 4 lines ?!!

**Comment by TheBorder** [comment]
1. mai dump folder cannot attach cause its 2 gb
2. 64 bit
3. the log 
[qcma_log.txt](https://github.com/codestation/qcma/files/644623/qcma_log.txt)

**Comment by codestation** [comment]
Tried to reproduce it without success. I even used your same user, folder structure and even the same game (from the logs) and managed to transfer it without errors. BTW, it only fails with that game or every transfer fails? From the logs i can see that it fails when transferring the file after the first KiB `PCSB00213_patch/mai_moe/eboot_origin.bin`

```
VitaMTP: PTP: reading event an error 0x02ff occurred
Error reading event from Vita.
VitaMTP ptp_write_func[346]: USB OUT (1) ==>
Sending of eboot_origin.bin failed. Code: 02FF
```

Can you use another cable/port? the problem seems like a hardware disconnection to me.

**Comment by TheBorder** [comment]
Ok i will try to mix up the things and i will let u know. 
What about the massive min it needs to transfer any game?
BTW i changed the vita id and the username for obvious reasons. :)

**Comment by TheBorder** [comment]
Yeah it was the port, though i was using the same port a month ago and qcma was working,still usb sticks and etc work on that port.
On the new port time was fixed.

Is there a fix on that?

**Comment by TheBorder** [comment]
Thanks for your help.
