### ISSUE TITLE
PS vita not detected on mac sierra via USB

### ISSUE THREAD

**Issue by mikelesagitter** [codestation/qcma#86]
Hi, I can't help to get this working,

I tried all configurations.
PS Vita running 3.60

Settings of qcma:

Offline mode checked
CMA protocol FW 3.30
Use this version for updates FW 3.60 HENkaku

PS vita is not even detected on a OS level (because for instance Parallels Desktop don't hint me where to connect the device)

**Comment by codestation** [comment]
Fixed by #109
