### ISSUE TITLE
Fedora 24 rpm error: empty %files file

### ISSUE THREAD

**Issue by wjyoung65** [codestation/qcma#87]
I'm trying to build fedora:24, and it ends with this error:

RPM build errors:
  Empty %files file /home/builder/rpmbuild/BUILD/qcma-0.3.12/debugfiles.list

See attached for the output from "./build.sh fedora:24"

Any chance this has already been solved? If not, any suggestions on how to go about debugging it? I've got beginner level experience with docker, and practically no experience with rpmbuild, though I can do some research to get up to speed.

[build.txt](https://github.com/codestation/qcma/files/724550/build.txt)

Thanks,
Wayne.

**Comment by wjyoung65** [comment]
Ok, I figured it out. The qcma.spec file needs a line added to it: %global debug_package %{nil}. I got the hint from [superuser.com](http://superuser.com/questions/1091529/rpm-build-error-empty-files-file-debugfiles-list)

**Comment by HWdriver** [comment]
how are you building it?

**Comment by xofi** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的邮件。
