### ISSUE TITLE
missing apps and games

### ISSUE THREAD

**Issue by zany130** [codestation/qcma#90]
whenever I connect to qcma with my vita it only lists 2 of the backed up apps and there the wrong size. going in backup manager in qcma shows the same apps but if I browse to the vita directory of qcma I can still see all my old apps and games

**Comment by zany130** [comment]
I had previously connected an idu vita so I tried to delete all the 000000000000 folders and now it says there nothing backup and again I checked my regular vita folder and its still there

**Comment by codestation** [comment]
The vita has to have an account to be able to use CMA, the 00000000000 folder indicated a lack of account.
