### ISSUE TITLE
Unable to update from 1.05 -> 3.60. 

### ISSUE THREAD

**Issue by meetajhu** [codestation/qcma#96]
I'm very new to PSVita hacking scene. My PSVita is **3g/wifi** model. 

This is the psp2-updatelist.xml which i'm using to update to 3.60. I have xml and PSP2UPDAT.PUP on the same folder

`<?xml version="1.0" encoding="UTF-8"?>
<update_data_list>
<region id="jp">
<np level0_system_version="01.500.000" level1_system_version="03.600.000" level2_system_version="03.600.000" map="03.600.000" />
<np_d level0_system_version="01.500.000" level1_system_version="03.600.000" level2_system_version="03.600.000" map="03.600.000" />
<version system_version="03.600.000" label="3.60">
<update_data update_type="full">
<image size="133676544">http://example.com/PSP2UPDAT.PUP</image>
</update_data>
</version>
<recovery spkg_type="systemdata">
<image spkg_version="01.000.010" size="56768512">http://example.com/PSP2UPDAT.PUP</image>
</recovery>
<recovery spkg_type="preinst">
<image spkg_version="01.000.000" size="128788480">http://example.com/PSP2UPDAT.PUP</image>
</recovery>
</region>
</update_data_list>
`
In QCMA settings i have checked "Offline mode" and tried CMA Protocol version **1.5** and **latest**. I even tried the DNS trick to update 3.60 still no luck. I'm unable to login to PSN account which is asking me to update. Do i need to activate the VIta or something?

**Comment by Konnoke** [comment]
Have you tried going in to QCMA settings -> tab “Other" -> “Use this version for updates" then picking FW 3.60?

In QCMA, the default is “FW 0.00 (Always up-to-date)".

**Comment by meetajhu** [comment]
@konnoke yeah I tried that still no change. It does throw me some error codes which I googled and found nothing. Let me post error codes which vita show in different secenarios.

**Comment by meetajhu** [comment]
Nevermind fixed by following this guide. This was the only way i could update to 3.60 without activating the Vita.

http://psx-scene.com/forums/f194/%5Bguide%5D-update-your-vita-previous-fw-releases-101831/
